---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-cloudflare
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
        - --source=istio-virtualservice
        - --domain-filter=mtaylor.io
        - --exclude-domains=home.mtaylor.io
        - --provider=cloudflare
        - --cloudflare-proxied
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-credentials
              key: api-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-route53
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
        - --source=istio-virtualservice
        - --domain-filter=home.mtaylor.io
        - --provider=aws
        - --aws-zone-type=public
        - --registry=txt
        - --txt-owner-id=k8s.home.mtaylor.io
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: route53-credentials
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: route53-credentials
              key: aws-secret-access-key
