# Name of the tunnel you want to run
tunnel: mtaylor-io
credentials-file: /etc/cloudflared/creds/credentials.json
# Serves the metrics server under /metrics and the readiness server under /ready
metrics: 0.0.0.0:2000
# Autoupdates applied in a k8s pod will be lost when the pod is removed or restarted, so
# autoupdate doesn't make sense in Kubernetes. However, outside of Kubernetes, we strongly
# recommend using autoupdate.
no-autoupdate: true
# The `ingress` block tells cloudflared which local service to route incoming
# requests to. For more about ingress rules, see
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
#
# Remember, these rules route traffic from cloudflared to a local service. To route traffic
# from the internet to cloudflared, run `cloudflared tunnel route dns <tunnel> <hostname>`.
# E.g. `cloudflared tunnel route dns example-tunnel tunnel.example.com`.
ingress:
- hostname: mtaylor.io
  service: https://istio-ingressgateway-public.istio-gateways.svc.cluster.local
  originRequest:
    originServerName: mtaylor.io
- hostname: www.mtaylor.io
  service: https://istio-ingressgateway-public.istio-gateways.svc.cluster.local
  originRequest:
    originServerName: www.mtaylor.io
- hostname: admin.mtaylor.io
  service: https://istio-ingressgateway-public.istio-gateways.svc.cluster.local
  originRequest:
    originServerName: admin.mtaylor.io
- hostname: iam.mtaylor.io
  service: https://istio-ingressgateway-public.istio-gateways.svc.cluster.local
  originRequest:
    originServerName: iam.mtaylor.io
- hostname: login.mtaylor.io
  service: https://istio-ingressgateway-public.istio-gateways.svc.cluster.local
  originRequest:
    originServerName: login.mtaylor.io
- hostname: argocd.mtaylor.io
  service: https://istio-ingressgateway-public.istio-gateways.svc.cluster.local
  originRequest:
    originServerName: argocd.mtaylor.io
- hostname: drone.mtaylor.io
  service: https://istio-ingressgateway-public.istio-gateways.svc.cluster.local
  originRequest:
    originServerName: drone.mtaylor.io
- hostname: systemloop.mtaylor.io
  service: https://istio-ingressgateway-public.istio-gateways.svc.cluster.local
  originRequest:
    originServerName: systemloop.mtaylor.io
- service: http_status:503
