
configurations:
- sealedsecrets.yml

namespace: cloudflare

commonLabels:
  app: cloudflared

configMapGenerator:
- name: cloudflared
  files:
  - ./config.yaml

secretGenerator:
- name: tunnel-credentials
  files:
  - ./tunnel-credentials-secret.json
  options:
    annotations:
      config.kubernetes.io/local-config: "true"

resources:
- ./deployment.yml
- ./tunnel-credentials-secret.json
