namespace: argocd
configMapGenerator:
- name: argocd-cm
  behavior: merge
  files:
  - config/oidc.config
  - config/resource.exclusions
resources:
- ../../../argocd
- ./applicationset.yml
- ./dex-client-secret.json
