namespace: argocd
configMapGenerator:
- name: argocd-cm
  behavior: merge
  files:
  - config/oidc.config
  - config/resource.exclusions
  literals:
  - url=https://argocd.mtaylor.io
- name: argocd-rbac-cm
  behavior: merge
  files:
  - config/policy.csv
resources:
- ../../../argocd
- ./applicationset.yml
- ./dex-client-secret.json
