---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-runner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-deployer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-runner
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-runner
subjects:
- kind: ServiceAccount
  name: kube-runner
roleRef:
  kind: Role
  name: kube-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-deployer
subjects:
- kind: ServiceAccount
  name: kube-deployer
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
