apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-mtaylor-io
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: iam
        args:
        - --postgres
        env:
        - name: HOST
          value: iam.mtaylor.io
        - name: EVENTS_HOST
          value: events.mtaylor.io
        - name: POSTGRES_DATABASE
          value: iam-mtaylor-io
        - name: POSTGRES_HOST
          value: db.postgres.svc.cluster.local
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: mtaylor-io
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password