apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mtaylor-io
patches:
  - path: iam-deployment-patch.yml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: iam-mtaylor-io
resources:
  - https://github.com/mtaylor91/mtaylor.io/deploy?ref=0.1.6
  - https://github.com/mtaylor91/iam-mtaylor-io/deploy?ref=0.1.47
  - https://github.com/mtaylor91/admin-mtaylor-io/deploy?ref=0.1.5
  - https://github.com/mtaylor91/events-mtaylor-io/deploy?ref=0.1.28
  - virtualservices.yml
  - events-secret.json
  - postgres-secret.json
configurations:
  - sealedsecrets.yml
configMapGenerator:
  - name: iam-mtaylor-io
    behavior: merge
    literals:
      - email=mike.charles.taylor@gmail.com
      - public-key=RZkhnsiJGOopSNuHfvwK81gxOn-CpMv3GSp1sn2AIyg=
  - name: events-mtaylor-io
    behavior: merge
    literals:
      - host=events.mtaylor.io
      - username=events-service
      - public-key=KnWDlcS4se8lt-g3g8gTw_k8YSd-2FXOkwnoAsH-pbM=
      - postgres-host=db.postgres.svc.cluster.local
      - postgres-port=5432
      - postgres-user=mtaylor-io
      - postgres-db=events-mtaylor-io
secretGenerator:
  - name: events-mtaylor-io
    behavior: merge
    files:
      - ./events-secret.json
    options:
      annotations:
        config.kubernetes.io/local-config: "true"
  - name: postgres
    files:
      - ./postgres-secret.json
    options:
      annotations:
        config.kubernetes.io/local-config: "true"
