apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mtaylor-io
patches:
  - path: iam-deployment-patch.yml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: iam-mtaylor-io
resources:
  - https://github.com/mtaylor91/event-server/deploy?ref=0.0.15
  - https://github.com/mtaylor91/mtaylor.io/deploy?ref=0.0.14
  - https://github.com/mtaylor91/iam-mtaylor-io/deploy?ref=0.1.25
  - https://github.com/mtaylor91/admin-mtaylor-io/deploy?ref=0.0.10
  - virtualservices.yml
  - postgres-secret.json
configurations:
  - sealedsecrets.yml
configMapGenerator:
  - name: iam-mtaylor-io
    behavior: merge
    literals:
      - email=mike.charles.taylor@gmail.com
      - public-key=GGYoznSvLoFBnlQ2Gs7AgxQgQ5qw3vS+YKTQ0divwN8=
secretGenerator:
  - name: postgres
    files:
      - ./postgres-secret.json
    options:
      annotations:
        config.kubernetes.io/local-config: "true"
