apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mtaylor-io
patches:
  - path: iam-deployment-patch.yml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: iam-mtaylor-io
  - path: status-deployment-patch.yml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: status-mtaylor-io
resources:
  - https://github.com/mtaylorio/mtaylor.io/deploy?ref=0.1.26
  - https://github.com/mtaylorio/iam-server/deploy?ref=0.1.63
  - https://github.com/mtaylorio/admin.mtaylor.io/deploy?ref=0.1.22
  - https://github.com/mtaylorio/events-server/deploy?ref=0.1.43
  - https://github.com/mtaylorio/status/deploy?ref=0.0.9
  - virtualservices.yml
  - events-secret.json
  - postgres-secret.json
configurations:
  - sealedsecrets.yml
configMapGenerator:
  - name: iam-mtaylor-io
    behavior: merge
    literals:
      - email=mike.charles.taylor@gmail.com
      - public-key=RZkhnsiJGOopSNuHfvwK81gxOn-CpMv3GSp1sn2AIyg=
  - name: events-mtaylor-io
    behavior: merge
    literals:
      - host=events.mtaylor.io
      - username=events-service
      - public-key=KnWDlcS4se8lt-g3g8gTw_k8YSd-2FXOkwnoAsH-pbM=
      - postgres-host=db.postgres.svc.cluster.local
      - postgres-port=5432
      - postgres-user=mtaylor-io
      - postgres-db=events-mtaylor-io
  - name: status-mtaylor-io
    behavior: merge
    literals:
      - PGHOST=db.postgres.svc.cluster.local
      - PGUSER=mtaylor-io
secretGenerator:
  - name: events-mtaylor-io
    behavior: merge
    files:
      - ./events-secret.json
    options:
      annotations:
        config.kubernetes.io/local-config: "true"
  - name: postgres
    files:
      - ./postgres-secret.json
    options:
      annotations:
        config.kubernetes.io/local-config: "true"
  - name: status-mtaylor-io
    behavior: merge
    options:
      annotations:
        config.kubernetes.io/local-config: "true"
