apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: pgadmin
        image: docker.io/dpage/pgadmin4:8.4
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin
              key: email
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin
              key: password
        - name: PGADMIN_LISTEN_PORT
          value: "8080"
        - name: PGUSER
          value: postgres
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: PGADMIN_CONFIG_CONFIG_DATABASE_URI
          value: "postgresql://$(PGUSER):$(PGPASS)@db.postgres.svc.cluster.local:5432/postgres"
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
