apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin
commonLabels:
  app: pgadmin
configurations:
- sealedsecrets.yml
resources:
- deployment.yml
- service.yml
- virtualservice.yml
- pgadmin-secret.json
- postgres-secret.json
secretGenerator:
- name: pgadmin
  files:
  - ./pgadmin-secret.json
  options:
    annotations:
      config.kubernetes.io/local-config: "true"
- name: postgres
  files:
  - ./postgres-secret.json
  options:
    annotations:
      config.kubernetes.io/local-config: "true"
