apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossmap-dev
configurations:
- sealedsecrets.yml
configMapGenerator:
- behavior: merge
  literals:
  - POSTGRES_DB=crossmap-dev
  - POSTGRES_HOST=db.postgres.svc.cluster.local
  - POSTGRES_PORT=5432
  - PUBLIC_KEY=o/SHgDx45Mh6KefbE8msSm9Jp9xYa1FjYhnLE7YWaHU=
  name: crossmap-api
secretGenerator:
- behavior: merge
  files:
  - ./crossmap-api-secret.json
  name: crossmap-api
  options:
    annotations:
      config.kubernetes.io/local-config: "true"
resources:
- https://github.com/crossmap-dev/api/deploy?ref=develop
- virtualservices.yml
- crossmap-api-secret.json
images:
- name: images.home.mtaylor.io/crossmap-api
  newTag: sha-bc9a0f8
