---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: koboldcpp
spec:
  gateways:
  - istio-gateways/home-mtaylor-io
  hosts:
  - koboldcpp.home.mtaylor.io
  http:
  - name: koboldcpp-routes
    route:
    - destination:
        host: koboldcpp.language-models.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sillytavern
spec:
  gateways:
  - istio-gateways/home-mtaylor-io
  hosts:
  - sillytavern.home.mtaylor.io
  http:
  - name: sillytavern-routes
    route:
    - destination:
        host: sillytavern.language-models.svc.cluster.local
        port:
          number: 80
