namespace: argocd
configMapGenerator:
- name: argocd-cm
  behavior: merge
  files:
  - config/oidc.config
  - config/resource.exclusions
  literals:
  - url=https://argocd.mtaylor.io
- name: argocd-rbac-cm
  behavior: merge
  files:
  - config/policy.csv
  literals:
  - policy.default=role:readonly
  - scopes='[email]'
resources:
- ../../../argocd
- ./applicationsets.yml
- ./dex-client-secret.json
