---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koboldcpp-models
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: openebs-lvmpv
---
