---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
