---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web
spec:
  gateways:
  - istio-gateways/mtaylor-io
  hosts:
  - mtaylor.io
  - www.mtaylor.io
  http:
  - name: mtaylor-io-socket-routes
    match:
    - uri:
        prefix: "/api/v1/socket"
    route:
    - destination:
        host: event-service.mtaylor-io.svc.cluster.local
        port:
          number: 80
  - name: mtaylor-io-web-routes
    route:
    - destination:
        host: web.mtaylor-io.svc.cluster.local
        port:
          number: 80
