apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
spec:
  template:
    spec:
      containers:
      - name: unifi
        image: docker.io/linuxserver/unifi-network-application:8.6.9
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Edmonton"
        - name: MONGO_USER
          value: "unifi"
        - name: MONGO_PASS
          value: "unifi"
        - name: MONGO_DBNAME
          value: "unifi"
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_AUTHSOURCE
          value: "admin"
        ports:
        - containerPort: 1900
          protocol: UDP
        - containerPort: 3478
          protocol: UDP
        - containerPort: 5514
          protocol: UDP
        - containerPort: 6789
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8880
          protocol: TCP
        - containerPort: 8843
          protocol: TCP
        - containerPort: 10001
          protocol: UDP
        volumeMounts:
        - name: unifi-config
          mountPath: /config
      volumes:
      - name: unifi-config
        persistentVolumeClaim:
          claimName: unifi-config
