apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    component: unifi
  includeSelectors: true
  includeTemplates: true
resources:
- ./deployment.yaml
- ./service.yaml
- ./volume.yaml
