apiVersion: v1
kind: Service
metadata:
  name: unifi
spec:
  type: LoadBalancer
  ports:
  - protocol: UDP
    port: 1900
    targetPort: 1900
  - protocol: UDP
    port: 3478
    targetPort: 3478
  - protocol: UDP
    port: 5514
    targetPort: 5514
  - protocol: TCP
    port: 6789
    targetPort: 6789
  - protocol: TCP
    port: 8080
    targetPort: 8080
  - protocol: TCP
    port: 8443
    targetPort: 8443
  - protocol: TCP
    port: 8880
    targetPort: 8880
  - protocol: TCP
    port: 8843
    targetPort: 8843
  - protocol: UDP
    port: 10001
    targetPort: 10001
