apiVersion: v1
kind: Service
metadata:
  name: unifi
spec:
  type: LoadBalancer
  ports:
  - name: discovery1
    protocol: UDP
    port: 1900
    targetPort: 1900
  - name: stun
    protocol: UDP
    port: 3478
    targetPort: 3478
  - name: syslog
    protocol: UDP
    port: 5514
    targetPort: 5514
  - name: speedtest
    protocol: TCP
    port: 6789
    targetPort: 6789
  - name: comms
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: web
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: http_portal
    protocol: TCP
    port: 8880
    targetPort: 8880
  - name: https_portal
    protocol: TCP
    port: 8843
    targetPort: 8843
  - name: discovery2
    protocol: UDP
    port: 10001
    targetPort: 10001
