---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mtaylor-io
spec:
  selector:
    istio: ingressgateway-public
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - '*.mtaylor.io'
    tls:
      httpsRedirect: true
  - port:
      name: https
      number: 443
      protocol: HTTPS
    hosts:
    - '*.mtaylor.io'
    tls:
      mode: SIMPLE
      credentialName: mtaylor-io-tls
