---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cloudflare
spec:
  acme:
    email: contact@mtaylor.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - selector:
        dnsZones:
        - "collectivelyintelligent.ca"
        - "collectivelyintelligent.net"
        - "crossmap.app"
        - "crossmap.dev"
        - "dev.mtaylor.io"
        - "mtaylor.io"
        - "subval.ca"
        - "subval.dev"
        - "subval.net"
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager-dns01-cloudflare
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-route53
spec:
  acme:
    email: contact@mtaylor.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - selector:
        dnsZones:
        - "home.mtaylor.io"
      dns01:
        route53:
          region: us-east-1
          accessKeyID: AKIA4Y3JCK3MXTPQ2DHX
          secretAccessKeySecretRef:
            name: cert-manager-dns01-route53
            key: secret-access-key
