issuer: https://login.mtaylor.io

storage:
  type: kubernetes
  config:
    inCluster: true

web:
  http: 0.0.0.0:8080

connectors:
- type: google
  id: google
  name: Google
  config:
    clientID: $GOOGLE_CLIENT_ID
    clientSecret: $GOOGLE_CLIENT_SECRET
    redirectURI: https://login.mtaylor.io/callback
    org: kubernetes

oauth2:
  skipApprovalScreen: true

staticClients:
- name: ArgoCD
  id: argocd-mtaylor-io
  secretEnv: ARGOCD_CLIENT_SECRET
  redirectURIs:
  - 'https://argocd.mtaylor.io/auth/callback'
