apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner
resources:
- https://github.com/actions/actions-runner-controller/releases/download/gha-runner-scale-set-0.9.1/actions-runner-controller.yaml
