apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
spec:
  volumeClaimTemplates:
  - metadata:
      name: ollama-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClassName: openebs-lvmpv
