apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
spec:
  template:
    spec:
      containers:
      - name: ollama
        resources:
          limits:
            cpu: 4000m
            memory: 16Gi
            nvidia.com/gpu: "2"
  volumeClaimTemplates:
  - metadata:
      name: ollama-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClassName: openebs-lvmpv
