apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    spec:
      containers:
      - name: mongodb
        image: docker.io/mongo:8.0.3
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "unifi"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "unifi"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-data
