apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sillytavern
configMapGenerator:
- name: sillytavern-config
  files:
  - config.yaml
resources:
- deployment.yml
- service.yml
