apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mtaylor-ca-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "mtaylor.ca"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: mtaylor-ca-credential # must be the same as secret
    hosts:
    - "mtaylor.ca"
