---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: subval-ca
spec:
  selector:
    istio: ingressgateway-public
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - 'subval.ca'
    - '*.subval.ca'
    tls:
      httpsRedirect: true
  - port:
      name: https
      number: 443
      protocol: HTTPS
    hosts:
    - 'subval.ca'
    - '*.subval.ca'
    tls:
      mode: SIMPLE
      credentialName: subval-ca-tls
